### PR TITLE
feat: esm only migration & rome setup

### PR DESCRIPTION
**Pull request by sachaw**
I'm opening this PR as I wish to use your package is a modern ESM application that requires import extensions.
Whilst rectifying that I simplified the associated tooling for the project:
1. Replace eslint & prettier with rome & removed config files
2. Moved to pnpm
3. modernised typescript config & build output
4. removed commonjs support (it can die in a fire)

Hopefully you can get on board with these changes, but please let me know if there are things you object with or want rectified, thanks!

### CODE REVIEW

**Review by LeoBorai — APPROVED** [review]
Great improvements! Thanks so much!

**Comment by EstebanBorai** [comment]
@sachaw looks like we are having lint issues! But overall LGTM!

**Comment by EstebanBorai** [comment]
Hi @sachaw!

Looks like tests cant run due to missing lock file. Perhaps just using pnpm setup is enough?

**Comment by EstebanBorai** [comment]
Merging! Will fix after merge!

**Pull request merged**
